### ISSUE TITLE
Betamax corrupts some responses

### ISSUE THREAD

**Issue by DeCarabas** [sigmavirus24/betamax#105]
Here's a simple test, which fails on betamax 0.60.0:

```
from betamax import Betamax
import requests

def test_get_url_image():
    http_session = requests.Session()
    url = 'https://www.crummy.com/software/BeautifulSoup/10.1.jpg'
    expected = http_session.get(url)

    with Betamax(http_session).use_cassette('test_get_url_image'):
        actual = http_session.get(url)

    assert expected.content == actual.content
```

It fails: actual.content is different than expected.content. I haven't looked very closely to see what's wrong, but something is.

**Comment by sigmavirus24** [comment]
Is this a regression from 0.5.x?

**Comment by sigmavirus24** [comment]
Also that URL isn't working for me. Do you have one that exhibits this behaviour?

**Comment by sigmavirus24** [comment]
Betamax stores response data in JSON. Arbitrary bytes *sometimes* are able to serialize to JSON which gives the false sense of "working". In this case, when they're deserialized, they're corrupted, as you point out. If you look at our [documentation](https://betamax.readthedocs.org/en/latest/configuring.html?highlight=preserve_exact_body_bytes#setting-default-cassette-options) we explain this and how to fix it.
