### ISSUE TITLE
Changes to betamax_recorder fixture's current_cassette persist between tests

### ISSUE THREAD

**Issue by rouge8** [sigmavirus24/betamax#108]
Config changes to `current_cassette` on the `betamax_recorder` pytest fixture persist between tests. I expected changes to `betamax_recorder.current_cassette` to behave like a pytest function-scoped fixture, where `betamax_recorder` would be new and clean on each test.

With betamax==0.7.0, pytest==2.9.2 and the following tests, whichever test runs second will fail:

```python
def test_headers(betamax_recorder):
    betamax_recorder.current_cassette.match_options.append('headers')
    assert betamax_recorder.current_cassette.match_options == [
        'method',
        'uri',
        'headers',
    ]

def test_body(betamax_recorder):
    betamax_recorder.current_cassette.match_options.append('body')
    assert betamax_recorder.current_cassette.match_options == [
        'method',
        'uri',
        'body',
    ]
```

Is this intended behavior?

**Comment by sigmavirus24** [comment]
No it's not. I have a fix for it though and can create a 0.7.1 quick fix release for this.

**Comment by sigmavirus24** [comment]
0.7.1 should fix this for you. Thanks for reporting it!

**Comment by rouge8** [comment]
Thanks for the super fast fix!

**Comment by sigmavirus24** [comment]
It does work, yes? (And you caught me in a slump while some deployments were finishing.)

**Comment by rouge8** [comment]
Yup!
