### ISSUE TITLE
Broken link in API docs

### ISSUE THREAD

**Issue by vitorbaptista** [sigmavirus24/betamax#109]
I'm trying to understand if I should preserve exact bytes or not, so I was looking around the docs for hints and in http://betamax.readthedocs.io/en/latest/api.html#forcing-bytes-to-be-preserved I found:

> You may want to force betamax to preserve the exact bytes in the body of a response (or request) instead of relying on the [opinions held by the library](http://betamax.readthedocs.io/en/latest/opinions). In this case you have two ways of telling betamax to do this.

This links to http://betamax.readthedocs.io/en/latest/opinions, which doesn't exist. I looked into the docs history a bit and couldn't find this page (haven't looked thoroughly, though).

**Comment by sigmavirus24** [comment]
Thanks for the report @vitorbaptista! I forgot how to write reStructuredText at some point ;)
