### ISSUE TITLE
Fail on invalid matchers?

### ISSUE THREAD

**Issue by bboe** [sigmavirus24/betamax#117]
`valididate_matchers` silently filters out matchers that do not exist. I'm guessing this is to be compatible with vcr. Please correct me if that assumption is wrong.

Ref: https://github.com/sigmavirus24/betamax/blob/51721667484bf25e581cc1435e7085dc53c1aad4/betamax/options.py#L8

I personally would like to hard-fail if a matcher is not found as in my recent testing night there were a number of times I forgot to register the matcher, and was unaware of why my updates to the matcher weren't working.

It would seem that I could manually set `match_options` on the cassette, resulting in an IndexError if a matcher does not exist. However, that doesn't seem like the accepted way to do things.

How would you feel about adding an option, or making it the default, to hard fail when a matcher doesn't exist? I think making the default to fail is good for users, but I understand if that's not desired due to incompatibility with VCR.

**Comment by sigmavirus24** [comment]
> How would you feel about adding an option, or making it the default, to hard fail when a matcher doesn't exist? I think making the default to fail is good for users, but I understand if that's not desired due to incompatibility with VCR.

Nah, it's fine. Makes perfect sense to me. =D :shipit:
