### ISSUE TITLE
Is it possible to write custom cassettes, without formatting, after following some syntax?

### ISSUE THREAD

**Issue by meetmangukiya** [sigmavirus24/betamax#138]
I want to use betamax to record and use cassettes that needs to provide authorization and I wouldn't like to write the credentials in the source code. 

Pardon me if this is already possible. I stumbled upon betamax while trying to find a way to test api response related functions, etc.

**Comment by sigmavirus24** [comment]
Hi @meetmangukiya did you happen to see http://betamax.readthedocs.io/en/latest/configuring.html#filtering-sensitive-data ? Is that somehow insufficient for you?

**Comment by meetmangukiya** [comment]
Hey @sigmavirus24 thanks for the link, I tried following the guide, but it seems that betamax doesn't record all the subsequent requests... see :point_down: 

```py
with recorder.use_cassette('github'):
    gh = Github.get_gh_obj(token)
    emoji_dict = gh.emojis()
    assert "smile" in emoji_dict
```
Github.get_gh_obj
```py
    @staticmethod
    def get_gh_obj(token):
        """
        :returns:   A github3 github object.
        """
        return github3.login(token=token)    
```

So, I think it only works for requests made directly? Requests from other objects are not recorded?

**Comment by sigmavirus24** [comment]
@meetmangukiya you really need to read the documentation. The problems you're having are explained very clearly there. Betamax does not globally magically monkey-patch every Requests Session you might instantiate. It only patches sessions you tell it to. As such, you've not provided the session to `github3` and it creates its own (if you're using the library I think you are).
