### ISSUE TITLE
Filter sensitive response headers

### ISSUE THREAD

**Issue by jerith** [sigmavirus24/betamax#42]
It would be useful to have a way to filter or replace potentially sensitive response headers (or response data in general, although I expect that's a harder problem) for which the value isn't known ahead of time.

My specific use case is a session cookie that is returned by the API I'm calling -- I don't want to store potentially active access mechanisms in the cassettes I push to my repository. In this particular case I don't care about having the header in my replays, but I'm sure there are other cases where a substitute value would be necessary.

(This is a feature I'd be happy to work on myself, but I can't think of a good design for it.)

**Comment by sigmavirus24** [comment]
This should be fixed by #104
