### ISSUE TITLE
Is "never" still a supported `record_mode` ?

### ISSUE THREAD

**Issue by samstav** [sigmavirus24/betamax#54]
I was using "never" as the record mode and I noticed cassettes were still being overwritten.

If not, just a couple changes in these files:

[`tests/regression/test_cassettes_retain_global_configuration.py`](https://github.com/sigmavirus24/betamax/blob/master/tests/regression/test_cassettes_retain_global_configuration.py)

[`docs/usage_patterns.rst`](https://github.com/sigmavirus24/betamax/blob/master/docs/usage_patterns.rst)

**Comment by sigmavirus24** [comment]
The docs and tests are wrong. We take our modes from [VCR](https://relishapp.com/vcr/vcr/v/2-9-3/docs/record-modes/none) so the docs and tests should be using "none". Sorry about that.

**Comment by samstav** [comment]
Cool. I'll fix PR#55.
