### ISSUE TITLE
official Debian package (please)

### ISSUE THREAD

**Issue by yarikoptic** [sigmavirus24/betamax#57]
following our brief discussion of possible stumbling stones in Debian, and while still listening to your nice talk at PyCon -- decided to ask if you could provide a Debian package of the betamax?  in my turn i could provide backport builds of those packages across Debian/Ubuntus from neurodebian

**Comment by sigmavirus24** [comment]
I'm up for that. I need to find a sponsor/mentor in DPMT though. /cc @paultag

**Comment by paultag** [comment]
I can sponsor. Let's sync at PyCon

**Comment by yarikoptic** [comment]
Awesome! Thanks guys... let me know if you get syncing :-)

**Comment by eriol** [comment]
I made a Debian package for betamax, maintained under the umbrella of DPMT:

https://anonscm.debian.org/cgit/python-modules/packages/betamax.git

@paultag since you wrote you could sponsor it I already sent a RFS, with all the details, to you by email. I hope it's fine.

**Comment by eriol** [comment]
Hi all,
betamax was uploaded[¹] so this issue can be closed! :smile:

[¹] https://packages.qa.debian.org/b/betamax/news/20160114T230018Z.html

**Comment by sigmavirus24** [comment]
Thanks @eriol!
