### ISSUE TITLE
decorator for @use_cassette

### ISSUE THREAD

**Issue by yarikoptic** [sigmavirus24/betamax#61]
I am yet to start using betamax (thanks to your talk at pycon 2015), but immediately caught a pattern I would have preferred to use -- by decorating test functions/methods instead of context manager.  I guess if decorating test methods it could automagically (or optionally) establish a session for the class.
FWIW vcr.py seems to provide similar functionality (```@vcr.use_cassette```)

**Comment by sigmavirus24** [comment]
In otherwords, something like:

```py
import betamax

@betamax.use_cassette('cassette_name')
def test_foo(session):
    session.get(...)
```

**Comment by sigmavirus24** [comment]
Hey @yarikoptic, sorry for the delay. I started working on this on the `feature/61` branch (c17d0cb).
