### ISSUE TITLE
recording/replaying sessions outside of the Python land

### ISSUE THREAD

**Issue by yarikoptic** [sigmavirus24/betamax#62]
Sorry for abusing issues, thus feel free to close right away.  I forgot to ask in our brief chat, and then didn't manage to locate you at PyCon to ask:  do you know any sane way to perform similar recording/replay (e.g. by providing an http proxy) of outside utilities -- e.g. of git -- when called from within Python tests?  thanks in advance for any hints.  Cheers!

**Comment by sigmavirus24** [comment]
I had a discussion with someone after the talk. They were talking about running processes in a container and setting up a firewall/proxy outside of it. I haven't done this though so I'm not sure if it would actually work very well.
