### ISSUE TITLE
Filter Sensitive Data

### ISSUE THREAD

**Issue by Sovietaced** [sigmavirus24/betamax#66]
Ruby VCR has a configuration option like so..

  c.filter_sensitive_data('API_KEY') { ENV['API_KEY'] }

which will replace the 'API_KEY' string in cassettes for the actual environment variable before running tests and save the environment value as 'API_KEY' when saving the cassettes. 

Does this library have a similar feature?

**Comment by sigmavirus24** [comment]
VCR calls it `define_cassette_placeholder` as well IIRC. It's documented [here](https://betamax.readthedocs.org/en/latest/api.html?highlight=placeholder#betamax.configure.Configuration.define_cassette_placeholder).

**Comment by Sovietaced** [comment]
@sigmavirus24 Thank You. Missed that.

**Comment by sigmavirus24** [comment]
No problem. I'm generally against aliasing things because the aliases become difficult to document. If you want to submit some patches to improve the docs, that's very welcome. I'm traveling and won't have time for a while.

**Comment by Sovietaced** [comment]
@sigmavirus24 Will do!
