### ISSUE TITLE
PyPI page is badly formatted

### ISSUE THREAD

**Issue by nedbat** [sigmavirus24/betamax#91]
The PyPI page for betamax looks junky.  I think this is because you are using a multi-line string for the value of `license` in setup.py.  The PyPI page has everything from the PKG-INFO file after the `License:` line (but not including the first line of the license.  If you change to `license="Apache 2.0"`, I think the PyPI page will fix itself.

**Comment by nedbat** [comment]
In the #pypa IRC channel, carljm said: "AFAIK the behavior in question here is not actually a behavior of PyPI, but of the method used to create the release via the PyPI API."

**Comment by sigmavirus24** [comment]
That explains a lot. Thanks @nedbat!
