### ISSUE TITLE
`requests.Response` is reused when `stream=True`

### ISSUE THREAD

**Issue by arhoyling** [sigmavirus24/betamax#95]
When you make the same streaming requests multiple times, you do not get any data after the first request.

```python
import betamax
import requests

session = requests.Session()
recorder = betamax.Betamax(session)

def stream(n):
    for k in range(1, n):
        response = session.get('http://httpbin.org/stream/3', stream=True)
        assert response.raw.read(), "Stream should not be empty. Attempt: %d" % k

with recorder.use_cassette('stream', record='once'):
    stream(10)
```

Betamax loads the cassette in the `use_cassette()` decorator and creates a unique `Interaction` with the associated recorded `requests.Response`. This `requests.Response` is reused each time `interaction.as_response()` is called but the stream is fully consumed after the first request.

Considering that Betamax is used for testing, would it be such an overhead to dynamically deserialize the recorded response every time an Interaction is used?

**Comment by sigmavirus24** [comment]
This makes sense. Would you like to tackle this @arhoyling?

**Comment by arhoyling** [comment]
Just made a pull request with the changes.

**Comment by sigmavirus24** [comment]
@arhoyling where did you make the pull request? There are none [here](https://github.com/sigmavirus24/betamax/pulls).

**Comment by arhoyling** [comment]
@sigmavirus24 you are right. Sorry about that.
I should have read the docs before trying a pull request.

[Here](https://github.com/sigmavirus24/betamax/pull/99)

**Comment by sigmavirus24** [comment]
This has been fixed.
